# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

sum = 0
current_term = 2
previous_term = 1
while current_term <= 4_000_000 do
  sum += current_term if current_term % 2 == 0
  temp = previous_term
  previous_term = current_term
  current_term += temp
end
puts sum